#!/usr/bin/env python3
"""Generate docs/reference.md from the reusable workflows' `workflow_call` contracts.

Usage:
  uv run python scripts/gen_workflow_reference.py          # rewrite docs/reference.md
  uv run python scripts/gen_workflow_reference.py --check  # exit 1 if out of date
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / ".github" / "workflows"
OUTPUT = ROOT / "docs" / "reference.md"

FLOWS = [
    ("security-audit-reusable.yml", "Security audit", "security-audit.md"),
    ("agent-plan-reusable.yml", "Plan", "plan-implement-review.md"),
    ("agent-implement-reusable.yml", "Implement", "plan-implement-review.md"),
    ("agent-review-reusable.yml", "Review", "plan-implement-review.md"),
]


def _cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _default(spec: dict) -> str:
    if "default" not in spec:
        return "—"
    value = spec["default"]
    if isinstance(value, bool):
        value = str(value).lower()
    return f"`{_cell(value)}`" if value != "" else '`""`'


def render() -> str:
    out = [
        "# Workflow reference",
        "",
        "<!-- Generated by scripts/gen_workflow_reference.py. Do not edit by hand. -->",
        "",
        "Inputs, secrets, and permissions of each reusable workflow, read from its `workflow_call` block.",
        "A Caller's `permissions:` must grant at least the permissions listed, or GitHub refuses the run.",
        "",
    ]
    for filename, title, guide in FLOWS:
        data = yaml.safe_load((WORKFLOWS / filename).read_text(encoding="utf-8"))
        on = data.get(True, data.get("on"))
        contract = on["workflow_call"]
        permissions = data.get("permissions") or {}
        out += [
            f"## {title}",
            "",
            f"`uses: mnaimfaizy/agent-kit/.github/workflows/{filename}@<tag>` — guide: [{guide}]({guide})",
            "",
            "**Caller permissions:** " + ", ".join(f"`{k}: {v}`" for k, v in permissions.items()),
            "",
            "| Input | Required | Default | Description |",
            "| ----- | -------- | ------- | ----------- |",
        ]
        for name, spec in (contract.get("inputs") or {}).items():
            required = "yes" if spec.get("required") else "no"
            out.append(f"| `{name}` | {required} | {_default(spec)} | {_cell(spec.get('description', ''))} |")
        out += ["", "| Secret | Required | Description |", "| ------ | -------- | ----------- |"]
        for name, spec in (contract.get("secrets") or {}).items():
            required = "yes" if spec.get("required") else "no"
            out.append(f"| `{name}` | {required} | {_cell(spec.get('description', ''))} |")
        out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    # Prettier owns table alignment, so compare cell content, not padding.
    rendered = render()
    if "--check" in argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if normalize(current) != normalize(rendered):
            print("docs/reference.md is stale. Run: uv run python scripts/gen_workflow_reference.py", file=sys.stderr)
            return 1
        print("docs/reference.md is up to date")
        return 0
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}; run `npx prettier --write docs/reference.md` to align tables.")
    return 0


def normalize(markdown: str) -> list[str]:
    lines = []
    for line in markdown.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("|"):
            cells = [c.strip() for c in stripped.strip("|").split(" | ")]
            if all(set(c) <= {"-", ":"} for c in cells):
                continue
            stripped = "|".join(cells)
        lines.append(stripped)
    return lines


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
